#TP_ARG_ENV_ID
#Made by Remy Aune
#08/09/2017

CFLAGS = -Wall -g -std=gnu99
EXECUTABLES = echoargenv \
	echoargenviron \
	exemple_environ_2

all : ${EXECUTABLES}
clean :
	@rm -f core *~ *.o *.out
	@rm -f ${EXECUTABLES}
